### ISSUE TITLE
ERROR when running the script

### ISSUE THREAD

**Issue by dheerajbred** [eagleoflqj/m3u8#1]
I got this error when I ran the command

```
E:\Flutter Apps\Downloads exper\a\m3u8>scrapy crawl m3u8 -a m3u8=https://up.imgupio.com/demo/birds.m3u8
Traceback (most recent call last):
  File "e:\installs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\installs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Installs\Python\Python38-32\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "e:\installs\python\python38-32\lib\site-packages\scrapy\cmdline.py", line 113, in execute
    settings = get_project_settings()
  File "e:\installs\python\python38-32\lib\site-packages\scrapy\utils\project.py", line 69, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "e:\installs\python\python38-32\lib\site-packages\scrapy\settings\__init__.py", line 287, in setmodule
    module = import_module(module)
  File "e:\installs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'm3u8.settings'
```

**Comment by eagleoflqj** [comment]
I typed the command you used on win10, then no error like this appeared.
Md5 of your merged ts file is d4ee856899e2857ae1be7d4fc5af50bb.
